baseURL = "https://lisbethaggerbeck.dk"
locale = "da-dk"
title = "LA ART"
description = "Official website of Lisbeth Aggerbeck"

timeZone = "Europe/Copenhagen"

enableGitInfo = true

disableKinds = [ 'taxonomy', 'term' ]

# Language settings
contentDir = "content/da"
defaultContentLanguage = "da"
defaultContentLanguageInSubdir = false

disableLanguages = [" "]

[params]
showPrices =  false

[languages.da]
  label = "Dansk"
  # Weight used for sorting.
  weight = 1
  direction = "ltr"


[languages.en]
  label = "English"
  # Weight used for sorting.
  weight = 2
  contentDir = "content/en"
  direction = "ltr"


[security]
allowContent = ['.*']

[security.node]
      disable = true
